<?php

namespace PublicBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentsByImage($image_id){
        $comments =  $this->createQueryBuilder('c')
            ->where('c.image = :image')
            ->setParameter('image', $image_id)
            ->getQuery()
            ->getResult();
        return $comments;
    }
    public function getCommentsByUser($user_id){
        $comments = $this->createQueryBuilder('c')
            ->where('c.user = :user')
            ->setParameter('user', $user_id)
            ->getQuery()
            ->getResult();
        return $comments;
    }
    public function editComment($id, $content){
        $this->createQueryBuilder('c')
            ->set('c.content', $content)
            ->where('c.id = id')
            ->setParameter('id', $id)
            ->getQuery()
            ->execute();
        return true;
    }
    public function deleteComment($comment_id){
        $this->createQueryBuilder('c')
            ->delete()
            ->where('c.id = :id')
            ->setParameter('id', $comment_id)
            ->getQuery()
            ->execute();
    }
}
