<?php

namespace PublicBundle\Repository;

/**
 * FaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaceRepository extends \Doctrine\ORM\EntityRepository
{
}
