# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  joined.date:
    class: PublicBundle\EventListener\JoinedOn
    tags:
      - { name: doctrine.event_listener, event: prePersist }

  upload.image:
    class: ProfileBundle\EventListener\UploadImage
    tags:
      - { name: doctrine.event_listener, event: prePersist }

  add.token:
    class: AdminBundle\EventListener\AddToken
    arguments: ['@security.authorization_checker', '@doctrine']
    tags:
      - { name: kernel.event_listener, event: security.interactive_login }